--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nxpinhum5326/VillagerNames
build-by-default: true
branches:
- master
projects:
  VillagerNames:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
